### ISSUE TITLE
[BUG] intronIC not working for example data and own data

### ISSUE THREAD

**Issue by RocesV** [glarue/intronIC#1] opened 2021-02-08 12:27 UTC
I am trying to run intronIC with example/own data and is not working.

COMMAND: 

`intronIC -g Homo_sapiens.Chr19.Ensembl_91.fa.gz -a Homo_sapiens.Chr19.Ensembl_91.gff3.gz -n homo_sapiens` (same as wiki)

FEEDBACK:

`[#] Starting intronIC [v1.1.1] run on [homo_sapiens (HomSap)]
[#] Run command: [/home/rocesv/anaconda3/envs/Seidr/bin/intronIC -g /mnt/e/Gymnosperms_Comparative/Gymnosperms_ComparativeGenomics/Introns_U2vsU12/Homo_sapiens.Chr19.Ensembl_91.fa.gz -a /mnt/e/Gymnosperms_Comparative/Gymnosperms_ComparativeGenomics/Introns_U2vsU12/Homo_sapiens.Chr19.Ensembl_91.gff3.gz -n homo_sapiens]
[#] Using [cds,exon] features to define introns
[#] [58933] introns found in [Homo_sapiens.Chr19.Ensembl_91.gff3.gz]
[#] [38681] introns with redundant coordinates excluded
[#] [8178] introns omitted from scoring based on the following criteria:
[#] * short (<30 nt): 66
[#] * ambiguous nucleotides in scoring regions: 0
[#] * non-canonical boundaries: 0
[#] * overlapping coordinates: 0
[#] * not in longest isoform: 8112
[#] Most common non-canonical splice sites:
[#] * AT-AG (16/328, 4.88%)
[#] * GT-TG (12/328, 3.66%)
[#] * GG-AG (12/328, 3.66%)
[#] * GA-AG (11/328, 3.35%)
[#] * AG-AG (10/328, 3.05%)
[#] [24] ([15] unique, [9] redundant) putatively misannotated U12-type introns corrected in [homo_sapiens.annotation.iic]
[#] [12074] introns included in scoring analysis
[#] Scoring introns using the following regions: [five, bp]
[#] Raw scores calculated for [20690] U2 and [387] U12 reference introns
[#] Raw scores calculated for [12074] experimental introns
[#] Training set score vectors constructed: [20690] U2, [387] U12
[#] Training SVM using reference data
Starting optimization round 1/5
Traceback (most recent call last):
  File "/home/rocesv/anaconda3/envs/Seidr/bin/intronIC", line 8, in <module>
    sys.exit(main())
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/intronIC/intronIC.py", line 5216, in main
    finalized_introns, model, u12_count, atac_count, demoted_swaps = apply_scores(
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/intronIC/intronIC.py", line 3804, in apply_scores
    model, model_performance = optimize_svm(
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/intronIC/intronIC.py", line 5512, in optimize_svm
    search_model, performance = train_svm(
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/intronIC/intronIC.py", line 5431, in train_svm
    model = GridSearchCV(
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'iid'`

PROBLEM TRACEBACK: 

**Starting optimization round 1/5
Traceback (most recent call last):
  File "/home/rocesv/anaconda3/envs/Seidr/bin/intronIC", line 8, in <module>
    sys.exit(main())
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/intronIC/intronIC.py", line 5216, in main
    finalized_introns, model, u12_count, atac_count, demoted_swaps = apply_scores(
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/intronIC/intronIC.py", line 3804, in apply_scores
    model, model_performance = optimize_svm(
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/intronIC/intronIC.py", line 5512, in optimize_svm
    search_model, performance = train_svm(
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/intronIC/intronIC.py", line 5431, in train_svm
    model = GridSearchCV(
  File "/home/rocesv/anaconda3/envs/Seidr/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'iid**

In both cases i have the same problem and the log is similar. Any idea? I am very interested on using this amazing tool.

Thank you in advance :)

PD: Running in conda env with python 3.9 (wsl 2 Ubuntu 20.04 Windows 10Pro)

**Comment by glarue** [comment] 2021-02-08 15:35
Hi @RocesV,

Thanks for bringing this to my attention; it looks like a `scikit-learn` regression; the `GridSearchCV` class used to have a parameter, `iid`, that defaulted to `True`, which `intronIC` set to `False` in the call. But as of `scikit-learn v0.22`, the default changed to `False` and as of `v0.24`, it's been removed entirely (see note under "iid" here: https://scikit-learn.org/0.21/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV). So, this will involve updating the `intronIC` installation config to require a newer version of `scikit-learn` after modifying the code to remove the `iid` argument.

I will make the change ASAP and push to the repo, at which point you can pull the latest code and see if it fixes the issue.

**Comment by glarue** [comment] 2021-02-08 19:43
Fixed in 196d26f82a9f4e64d49133aa679b89b3733ea49f (and codified in release `v1.2.0`). Thanks @RocesV!

**Closed by glarue** 2021-02-08 19:43 UTC
